"""MinIO storage manager for MetaWeave."""

from __future__ import annotations

import io
import os
from datetime import timedelta

from minio import Minio

BUCKETS = ("raw-papers", "raw-texts", "extracted-structures")


class StorageManager:
    """Thin wrapper around the MinIO Python client.

    Environment variables
    ---------------------
    MINIO_ENDPOINT        Internal endpoint used for API calls (default: localhost:9000).
    MINIO_ACCESS_KEY      MinIO access key (default: minioadmin).
    MINIO_SECRET_KEY      MinIO secret key (default: minioadmin).
    MINIO_PUBLIC_ENDPOINT Public-facing endpoint used by the dedicated pre-signed-URL
                          client.  MinIO signs the URL with this hostname so that the
                          browser's request passes signature validation without any
                          host rewriting.  Example: localhost:9000
                          If unset, the internal endpoint is used for both clients.
    """

    def __init__(self) -> None:
        endpoint = os.environ.get("MINIO_ENDPOINT", "localhost:9000")
        access_key = os.environ.get("MINIO_ACCESS_KEY", "minioadmin")
        secret_key = os.environ.get("MINIO_SECRET_KEY", "minioadmin")
        self._public_endpoint: str = os.environ.get("MINIO_PUBLIC_ENDPOINT", endpoint)

        # Internal client — used for all storage operations (upload, download, listing).
        # Must resolve the internal Docker hostname (e.g. "minio:9000").
        self.client = Minio(endpoint, access_key=access_key, secret_key=secret_key, secure=False)

        # Public client — used *only* for generating pre-signed URLs.
        # It is configured with the browser-accessible endpoint so that MinIO
        # computes the HMAC signature over the public hostname.  A URL signed
        # with "localhost:9000" will pass MinIO's signature check when the
        # browser requests it at "localhost:9000", avoiding SignatureDoesNotMatch.
        self._public_client = Minio(
            self._public_endpoint,
            access_key=access_key,
            secret_key=secret_key,
            secure=False,
        )

        self._ensure_buckets()

    # ------------------------------------------------------------------
    # Bucket helpers
    # ------------------------------------------------------------------

    def _ensure_buckets(self) -> None:
        """Create the required buckets if they do not exist."""
        for bucket in BUCKETS:
            if not self.client.bucket_exists(bucket):
                self.client.make_bucket(bucket)

    # ------------------------------------------------------------------
    # Upload
    # ------------------------------------------------------------------

    def upload_pdf(self, bucket: str, object_name: str, data: bytes) -> str:
        """Upload a PDF (as *bytes*) to MinIO and return the object name."""
        self.client.put_object(
            bucket,
            object_name,
            io.BytesIO(data),
            length=len(data),
            content_type="application/pdf",
        )
        return object_name

    # ------------------------------------------------------------------
    # Pre-signed URL (with public-endpoint rewrite)
    # ------------------------------------------------------------------

    def presigned_url(
        self,
        bucket: str,
        object_name: str,
        expires: timedelta = timedelta(hours=1),
    ) -> str:
        """Return a browser-accessible pre-signed GET URL.

        The URL is generated by ``_public_client``, which is configured with
        ``MINIO_PUBLIC_ENDPOINT`` (e.g. ``localhost:9000``).  Because MinIO
        computes the HMAC signature using the client's configured host, the
        resulting signature is valid for requests arriving at that same public
        host — no hostname rewriting is needed and the signature is never
        invalidated.
        """
        return self._public_client.presigned_get_object(bucket, object_name, expires=expires)

    # ------------------------------------------------------------------
    # Listing
    # ------------------------------------------------------------------

    def list_objects(self, bucket: str, prefix: str = "") -> list[str]:
        """Return a list of object names under *prefix* in *bucket*."""
        return [
            obj.object_name
            for obj in self.client.list_objects(bucket, prefix=prefix, recursive=True)
        ]
